services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql+pymysql://root:senha123@db:3306/appdb
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=senha123
      - MYSQL_DATABASE=appdb
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "8081:8080"

  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  db_data:
  portainer_data:
